# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Comm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=140)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('post_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('img_hero_src', models.CharField(blank=True, max_length=255)),
                ('img_hero_title', models.CharField(blank=True, max_length=80)),
                ('img_thumb_src', models.CharField(blank=True, max_length=255)),
                ('img_thumb_title', models.CharField(blank=True, max_length=80)),
                ('excerpt', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
        migrations.CreateModel(
            name='CommType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=140)),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=140)),
                ('img_thumb_src', models.CharField(blank=True, max_length=255)),
                ('img_thumb_title', models.CharField(blank=True, max_length=80)),
                ('img_gallery_src', models.CharField(blank=True, max_length=255)),
                ('img_gallery_title', models.CharField(blank=True, max_length=80)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('short_desc', models.CharField(blank=True, max_length=255)),
                ('long_desc', models.TextField(blank=True)),
                ('img1_src', models.CharField(blank=True, max_length=255)),
                ('img1_title', models.CharField(blank=True, max_length=80)),
                ('img2_src', models.CharField(blank=True, max_length=255)),
                ('img2_title', models.CharField(blank=True, max_length=80)),
                ('img3_src', models.CharField(blank=True, max_length=255)),
                ('img3_title', models.CharField(blank=True, max_length=80)),
                ('client', models.CharField(blank=True, max_length=200)),
                ('categories', models.ManyToManyField(default=None, to='core.Category')),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
        migrations.AddField(
            model_name='comm',
            name='commtype',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.CommType'),
        ),
        migrations.AddField(
            model_name='comm',
            name='tags',
            field=models.ManyToManyField(default=None, to='core.Tag'),
        ),
    ]
